### ISSUE TITLE
Modify Collections#index to only show "object_type: collection" or update save process

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl-fetcher#84]
Currently `Purl` model only saves `'//*[name()="fedora:isMemberOfCollection"]'` as a `Collection`. Should this be updated or should the query be updated?

**Comment by LynnMcRae** [comment]
Not sure of the context of question since this seems to be talking about two different but related things.  Are we talking about the Purl solr model or how it is queried? Object_type says what kind of entity THIS object is, a collection vs item, while isMemberOfCollection is a relationship found in items to say what collection they are a member of.  A doc that is showing a collection and its members would be interested in both but has presumably started with the collection object as the basis for the request and only needs to find its members. Apologies if I'm off point.

**Comment by mejackreed** [comment]
Currently, purl-fetcher only understands if something should be returned on the collections endpoint if (coming from the purl xml):

`'//*[name()="fedora:isMemberOfCollection"]'`

Is that the correct logic? Or should it be something like:

```ruby
if object_type == 'set' || object_type == 'collection`
```

**Comment by LynnMcRae** [comment]
If by collections endpoint you mean a request like "purl-fetcher.../collections/druid:xp090gg8814" then you are given the druid for the collection record itself, so technically there's no need to query for it (except to the extent that fetching the solr by ID is still a query). It should verify that the named druid is in fact a collection record by checking for object_type == 'collection`, but otherwise you are there.  You then need the search for isMemberOfCollection, referring to this druid, to populate the rest of the document with membership information.

**Comment by LynnMcRae** [comment]
just to get this info into the ticket, the question was about the unadorned /collections endpoint, not collections/[druid] (my misunderstanding), and the answer was a clean query on just object_type=collection
